### ISSUE TITLE
delay in logout to take effect

### ISSUE THREAD

**Issue by mostafashr** [ibuetler/docker-keycloak-traefik-workshop#2]
Hi, nice guide you have on docker-keycloak-traefik-workshop
I"m currently running into an issue in your guide.
I have set the the keycloak and traefik up and it work correctly but when I call the logout route in keycloak OpenID configuration the session in keycloak sessions get deleted immediately but the traefik still route request to protected service for 30 second or so. After that I got redirected to login page to re-login. I think some sort of caching is happening in the traefik. 
How can I fix the issue to logout immediately and stop routing request to protected service without  delay?

**Comment by ibuetler** [comment]
Thank you for your comment. I see. Traefik is not aware of keycloak sessions and JWT tokens. Did you do the workshop until keycloak-gatekeeper? Thus, I would assume keycloak-gatekeeper is accepting the JWT for the next 30 seconds. May this timeout can be configured in keycloak-gatekeeper? If you figured out how, I would be eager to learn more about this. 

Regards
Ivan

**Comment by mostafashr** [comment]
Thank you for the Reply.
Yes your right. I thought it was Traefik issue but it was Keycloak gatekeeper. It was my mistake in calling the logout URL.I called the Keycloak discovery logout URL but I should have called the gatekeeper logout URL. it was stated clearly in gatekeeper documentation.  "/oauth/logout?redirect=url" route immediately logout user and close the session.

**Comment by ibuetler** [comment]
Awesome. Thank you for your reply.
