### ISSUE TITLE
Keycloak data in the app beyond the auth

### ISSUE THREAD

**Issue by niekvlessert** [ibuetler/docker-keycloak-traefik-workshop#3]
Thank you for this great tutorial! Everything works fine overhere. 

What I would like to know is how to access data in Keycloak from the currently logged in user from the app beyond the authentication, so that it can for example show the user name and get certain permissions from Keycloak. I can imagine it's the rest interface and I need some session information or something, but I don't really know where to start.

Got any tips?

**Comment by ibuetler** [comment]
If you are using OIDC (Open-ID-Connect), such information will be sent to you by JWT token. UserID, E-Mail and such will be sent without changing the keycloak configuration. If you want to get roles, permissions and more, you need to configure keycloak and define if these properties shall be added to the JWT token.

**Comment by niekvlessert** [comment]
Thx, just the tip I needed! Might add a line to the tutorial. Regards Niek
