### ISSUE TITLE
gatekeeper

### ISSUE THREAD

**Issue by ddmunhoz** [ibuetler/docker-keycloak-traefik-workshop#5]
First thank you for this amazing guide!

I got it working perfectly, but now I have a question for you:

I configured the gatekeeper for ttyd. But lets suppose I want to have more services, like other containers like grafana, portainer. How should I configure the gatekeeper to support multiple services and not only ttyd ?

Thanks!

**Comment by ibuetler** [comment]
One gatekeeper per service. Multiple services behind the same gatekeeper is currently not supported by gatekeeper. Regards, Ivan
